#!/bin/bash

PATTERN=*
PATTERN_DIR=*
MIN_DEPTH=1
MAX_DEPTH=5
FILE_TYPE=r

while [ -n "$1" ]; do
  case $1 in
    -p|--pattern)        PATTERN=${2};    shift 2;;
    --pattern-dir)       PATTERN_DIR=$2;  shift 2;;
    --min|--mindepth)    MIN_DEPTH=$2;    shift 2;;
    --max|--maxdepth)    MAX_DEPTH=$2;    shift 2;;
    -*)
      [[ "$1" =~ f ]] && FILE_TYPE=f
      [[ "$1" =~ d ]] && FILE_TYPE=d
      [[ "$1" =~ r ]] && FILE_TYPE=r
      shift 1;;
    *) break;;
  esac
done

rm_namechar() {
  echo "$1" \
  | sed \
    -e "s#\\.#ThEDoT#g" \
    -e "s#/#ThESlAsH#g" \
    -e "s#-#ThEMiNuS#g" \
    -e "s#[[:cntrl:]|[:punct:]|[:blank:]]#_#g" \
    -e "s#ThEDoT#.#g" \
    -e "s#ThESlAsH#/#g" \
    -e "s#ThEMiNuS#-#g" \
    -e "s#/_#/#g" \
  | tr -s '_-'
}

do_mv () {
  local dst=`rm_namechar "$1"`
  echo [$2]: $1
  echo "         -> " $dst
  test "$1" == "$dst" || mv "$1" "$dst"
}

if test "$FILE_TYPE" == "r"; then
  is_d=1
  is_f=1
elif test "$FILE_TYPE" == "d"; then
  is_d=1
  is_f=
elif test "$FILE_TYPE" == "f"; then
  is_d=
  is_f=1
fi

IFS=$(echo -en "\n\b")
for ((i=$MIN_DEPTH; i<=$MAX_DEPTH; i++));
do
  test "$is_d" == 1 && for f in `find . -type d -mindepth $i -maxdepth $i -name "$PATTERN_DIR"`;
  do
    do_mv "$f" "Directory"
  done
done

test "$is_f" == 1 && for f in `find . -type f -mindepth $MIN_DEPTH -maxdepth $MAX_DEPTH -name "$PATTERN"`;
do
  do_mv "$f" "   File  "
done

